{{- if and .Values.persistence.cache.enabled (not .Values.persistence.cache.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jellyfin.cachePVCName" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
{{- with .Values.persistence.cache.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.cache.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size | quote }}
{{- if .Values.persistence.cache.storageClass }}
{{- if (eq "-" .Values.persistence.cache.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.cache.storageClass }}"
{{- end }}
{{- end }}
{{- end }}