apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitwarden-rs.fullname" . }}-env
  labels:
    {{- include "bitwarden-rs.labels" . | nindent 4 }}
data: 
  {{- range $key, $val := .Values.bitwardenConfig }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end}}
