{{- if (not .Values.credentials.useExistingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  labels:
{{ include "bitwarden-rs.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminToken: {{ randAlphaNum 64 | quote }}
  mysql-root-password: {{ randAlphaNum 12 | quote }}
  mysql-password: {{ randAlphaNum 12 | quote }}
{{- end }}